
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://goxpejofxjvcilfoyrxs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdveHBlam9meGp2Y2lsZm95cnhzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNDc0NDgsImV4cCI6MjA2MDkyMzQ0OH0.Giew8VRVChAks1ooUc3N3oTbMDjFVTzGnr9IExIirYs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});
